### ISSUE TITLE
Configure the database (PostgreSQL + Supabase)

### ISSUE THREAD

**Issue by amanda-a-reis** [GuilhermeABRoncari/cinemenu-api#17]
_Configurar o banco de dados de desenvolvimento no projeto._

___

Para desenvolvimento, vamos utilizar um banco de dados na nuvem gratuito.

Utilizaremos o [Supabase](https://supabase.com/), que é um serviço open-source.

A URI de conexão já foi criada na conta do projeto, para não precisar configurar em uma conta pessoal (entrar em contato com @amanda-a-reis para pegar a URI de conexão).

Caso haja alguma dúvida sobre como configurar no projeto, acessar a [documentação](https://supabase.com/docs/guides/database) do Supabase.

**Comment by GuilhermeABRoncari** [comment]
Tudo certo, esse banco informado foi anexado ao perfil de < dev > do spring. Não recomendo usar na produção pois será onde a maioria dos testes feitos a mão vão estar.
