### ISSUE TITLE
Create the structure of folders related to the data layer

### ISSUE THREAD

**Issue by amanda-a-reis** [GuilhermeABRoncari/cinemenu-api#18]
_Task arquitetural: estrutura de pastas para banco de dados._

___

Conforme foi discutido, criar a estrutura de pastas da camada de banco de dados para o projeto, de modo que o SGBD (no nosso caso, postgreSQL) seja abstraído na implementação.

**Comment by GuilhermeABRoncari** [comment]
Qual o nome eu deveria dar para a branch nova dessa issue? eu pensei em algo como: git checkout setup/18/internal_package_structure

é só um exemplo.

**Comment by GuilhermeABRoncari** [comment]
Criei toda a estrutura de pastas mas não é possível fazer nenhum commit. As pastas não contam como arquivos que alteram o código em algo.
