### ISSUE TITLE
Add lint dependencies

### ISSUE THREAD

**Issue by amanda-a-reis** [GuilhermeABRoncari/cinemenu-api#5]
_O inutito dessa task é adicionar uma ferramenta de Lint para que o código fique padronizado._

___

Branch

```bash
git checkout -b setup/5/add_lint_dependencies_and_rules
```

Referência:

https://medium.com/@rafaelvicio/mantenha-seu-c%C3%B3digo-java-limpo-com-sonarlint-951a8f375ece

Esse artigo recomenda o SonarLint, mas pode ser outra ferramenta também. 
O importante é adicionar uma ferramenta que ajude na consistência do código.

**Comment by GuilhermeABRoncari** [comment]
SonarLint plugin install in my personal computer. Link for SonarLint homepage: https://plugins.jetbrains.com/plugin/7973-sonarlint
