### ISSUE TITLE
Implementar CRUD de item da lista (midias)

### ISSUE THREAD

**Issue by NewtonCesarRoncari** [GuilhermeABRoncari/cinemenu-api#56]
_Criar endpoints necessários para adição, atualização, busca e deleção das midias nas listas._

___

 ## Enpoints

1.  Verbo **POST**  endpoint **lists/media** parametro id_list -> salva os dados da midia na lista do id passado

`Json da requisição`
 ```json
{
   "medias": [
       {
        "id_tmdb": "fjeijIFE88",
        "media_type": "MOVIE",
        "note": "Gostei muito desse filme",
        "user_rating": 8.0,
        "watched": false,
       },
       {
        "id_tmdb": "fFE88",
        "note": "Esse eu nao gostei",
        "media_type": "MOVIE",
        "user_rating": 2.0,
        "watched": true,
       },
    ]
}
```
___

2.  Verbo **PUT**  endpoint **lists/media** parametro id_media -> atualiza os dados da midia do id passado

`Json da requisição`
 ```json
{
        "note": "Gostei muito desse filme",
        "user_rating": 8.0,
        "watched": false,
}
```

___

3.  Verbo **DELETE**  endpoint **lists/media** parametro id_media -> deleta os dados da midia do id passado
___

4.  Verbo **GET**  endpoint **lists/media** parametro id_list -> retrona as midias da lista, de maneira paginada

`Json da retorno`
 ```json
{
   "page" :1,
   "medias": [
       {
        "id": "ffrKUHFKHK"
        "id_tmdb": "fjeijIFE88",
        "media_type": "MOVIE",
        "note": "Gostei muito desse filme",
        "user_rating": 8.0,
        "watched": false,
       },
       {
        "id": "ffrffffFKHK"
        "id_tmdb": "fFE88",
        "media_type": "MOVIE",
        "note": "Esse eu nao gostei",
        "user_rating": 2.0,
        "watched": true,
       },
    ]
}
```

**Comment by GuilhermeABRoncari** [comment]
Não seria interessante também registrar onde essa midia pode ser consumida? (Netflix, Amazon Prime, HBO Max, etc...)

**Comment by NewtonCesarRoncari** [comment]
> Não seria interessante também registrar onde essa midia pode ser consumida? (Netflix, Amazon Prime, HBO Max, etc...)

A informação de onde a midia pode ser consumida, virá no endpoint de media_detail nessa issue 
 - #53
