### ISSUE TITLE
Configure initial CI with GitHub Actions

### ISSUE THREAD

**Issue by amanda-a-reis** [GuilhermeABRoncari/cinemenu-api#8]
_A intenção dessa task é a criação e configuração inicial do ambiente de CI que vai rodar no GitHub Actions, a princípio._

___ 

Branch

```bash
git checkout -b ci/8/config_initial_ci
```

#### O que é CI (Continous Integration)

https://gabriel-faraday.medium.com/o-que-%C3%A9-ci-cd-onde-eu-uso-isso-57e9b8ad8c73

#### Implementar na prática

Como referência, existe a documentação do próprio GitHub: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

**Comment by GuilhermeABRoncari** [comment]
In this task a will need Newtinho's help.
